### ISSUE TITLE
Mobile Preview before Print

### ISSUE THREAD

**Issue by SahilAmaan** [tr3v3r/react-native-esc-pos-printer#148]
Is there any way that I can check print (as kind of preview) in my Mobile before printing?

**Comment by tr3v3r** [comment]
@SahilAmaan agrees that would be useful feature, but unfortunately, since all printing is managed by sending print commands directly to the printer, there is no out-of-the-box solution to preview the receipt. 

The the only way I see is to implement it. If you have an idea/time - please welcome. From my side, I'll put this idea the roadmap list
