### ISSUE TITLE
EXC_BAD_ACCESS when running the code on a device (iPad)

### ISSUE THREAD

**Issue by abosaqr** [tr3v3r/react-native-esc-pos-printer#44]
Hello,

thanks for the work put into the library, I am having an issue after building then executing the app.

This is the issue
![image](https://user-images.githubusercontent.com/37481626/150693048-50e0ca5e-11c7-440a-a8ae-6ec8d186cfb6.png)

This is the stack
![image](https://user-images.githubusercontent.com/37481626/150693007-fdcb16c2-4586-44d3-8f44-4e2c074cbeb4.png)

From the stack it seems the library (Flipper) is trying to create or get a certificateSigningRequest but not being successful

do you think it is  a configuration issue?

kind regards,
abosaqr

**Comment by abosaqr** [comment]
@update:

in the simulator there is no issue, the exception happens in physical device: an iPad Air (4th generation), software version 15.0.

**Comment by abosaqr** [comment]
@update

disabling flipper by commenting the line in ```ios/Podfile``` makes it work again.
```
use_flipper!()
```

i don't like removing things i don't know, so is this an issue or not? or better question, what functionality am I losing without flipper?

thanks

**Comment by fragilehm** [comment]
Hi, @abosaqr I am not sure what is the real issue here, but a flipper is just an Inspector which is helpful for developing as it gives you a clear view of the layout and network actions. But this will not affect your production (release) app.

**Comment by yedidyak** [comment]
Hi, we are getting this issue as well. My guess is that something in this library conflicts with the version of OpenSSL-Universal that Flipper depends on.

**Comment by yedidyak** [comment]
By the way, we're getting this on any iOS device when running debug with Flipper running, not just iPads.

**Comment by yedidyak** [comment]
The reason for this crash is that the EpsonEposSDK has embedded openSSL library with conflicts with the OpenSSL-Univeral pod brought and used by Flipper. So it's in the actual Epson SDK, not this library. Which is awesome btw.

**Comment by lucienbl** [comment]
Hello, I am facing this issue as well, does anyone has a workaround for that without removing flipper ? I need flipper 😬 Thanks in advance!

**Comment by yedidyak** [comment]
Yes, you can add this pod only on Release and Release-Store configurations in the Podfile. Then you can still use Flipper in Debug builds.

**Comment by lucienbl** [comment]
@yedidyak thank you very much for your quick reply. But adding this pod only to Release configurations will prevent me to use it while I'm developing, right ? If there's no other solution maybe it's even better to remove Flipper instead, sadly 😄

**Comment by tr3v3r** [comment]
> The reason for this crash is that the EpsonEposSDK has embedded openSSL library with conflicts with the OpenSSL-Univeral pod brought and used by Flipper. So it's in the actual Epson SDK, not this library. Which is awesome btw.

Hi! Thanks for helping! How did you figure out that issue with this conflict? I mean OpenSSL dependency?

**Comment by cody0704** [comment]
I don't have the EXC_BAD_ACCESS issue after I remove Flipper

**Comment by cody0704** [comment]
@tr3v3r 

Hope you or someone else can verify this

## Environment

```
"react-native": "0.70.1",
"react-native-esc-pos-printer": "^2.1.0",
```

## To Reproduce

Reference the Flipper version to the [podfile.lock](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/example/ios/Podfile.lock) version in the example so that OpenSSL-Universal can be specified as 1.1.180.

After I set it up, `EXC_BAD_ACCESS` does not appear.

* `<project>/ios/Podfile`

```
...

:flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.93.0', 
'Flipper-Folly' => '2.6.7', 'Flipper-Glog' => '0.3.6', 'Flipper-DoubleConversion' => '3.1.7', 
'OpenSSL-Universal' => '1.1.180' }),
...
```

**Comment by sisoalbert** [comment]
> @update
> 
> disabling flipper by commenting the line in `ios/Podfile` makes it work again.
> 
> ```
> use_flipper!()
> ```
> 
> i don't like removing things i don't know, so is this an issue or not? or better question, what functionality am I losing without flipper?
> 
> thanks

Folks using this workaround must remove to delete pod and pod install again after  commenting out > ```
># use_flipper!()
> ```

**Comment by 592da** [comment]
Hey @yedidyak !
You think it's possible to create a patch to solve the conflict for the openssl between EpsonEposSDK & Flipper?

**Comment by hoang-nha** [comment]
I am facing a similar issue, please help me with the solution.
"react-native-esc-pos-printer": "^2.5.1",
"react-native-flipper": "^0.201.0",
"react-native": "0.72.3",

**Comment by tr3v3r** [comment]
Thanks, everybody for your help!

I've investigated a bit and found the version of OpenSSL lib used in EPSO iOS SDK and found a workaround that should work. (At least works for me):

1) `yarn add patch-package postinstall-postinstall`. Details [here](https://www.npmjs.com/package/patch-package)
2) Put [this file](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/example/Flipper-Folly.podspec) to the root folder of your app.
3) In the root dir create `patches` folder and create file `react-native+{you RN version}.patch`. With the [this content.](https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/example/patches/react-native%2B0.70.5.patch)
4) in package.json in the `scripts` section add:
```
 "scripts": {
   "postinstall": "patch-package"
 }
 ```
 Now you can run `yarn` or `npm` and re-run `pods` installation.
 
 I've added this workaround to the example folder. Corresponding [commit here](https://github.com/tr3v3r/react-native-esc-pos-printer/commit/13f4ceefa11cd29ab98a2b83d9196a80e2847576).
 
 **Explanation**: 
 Since the crash was caused by the conflict between versions of the OpenSSL lib in the Flipper_Folly dependencies and iOS ESC POS SDK dependencies, I've tried to apply the version from the SDK to Flipper_Folly. For that, I had to modify Flipper_Folly podspec and specify manually the needed version for OpenSSL lib.
 
For me, it works. I've tried to run the app on a real device and tried to debug using Flipper. 
I'd really appreciate it if someone could share the feedback if the workaround works for them also.

P.S.
And finally, we're trying to reach DEV team of EPSON iOS SDK to ask them to help with this also. Probably bump the version of the OpenSSL or at least provide a bit less "hacky" solution.
