### ISSUE TITLE
Printing Images Estimation?

### ISSUE THREAD

**Issue by abdulla-khalil** [tr3v3r/react-native-esc-pos-printer#6]
hello, 

thanks for the hard work for this library.

Just wanted to ask if there is an estimation for the printing images feature? (hopefully iOS and Android)?
 Does not have to be an accurate estimation.

regards

**Comment by tr3v3r** [comment]
Hello @abdulla-khalil,

I need this feature too actually, so I'll try to do my best to do it in the next few weeks ;)

**Comment by abdulla-khalil** [comment]
will be keeping an eye on it. many thanks.

**Comment by tr3v3r** [comment]
I'll keep you posted on the progress 👍

**Comment by zchryst** [comment]
Hey @tr3v3r - is there anything I can do to help with this?

**Comment by tr3v3r** [comment]
@zchryst Hi! Sorry for that but I have a lot of activities now (( 
Actually to implement this functionality we need to change a bit the way of printing.

So instead of using binary data and external lib (esc-pos-encoder) we need to print using the printing methods provided by SDK itself (i.e. printText, align, printImage and etc.).

Because, if add just print image method, it will be just possible to print an image at the beginning or at the end of the print layout.

If you have capacity / possibilities to do it right now, I'd be really grateful. 

But anyway I definitely will do it in the near future ( I hope :)  )

**Comment by zchryst** [comment]
@tr3v3r Yeah - I've got a little bit of capacity at this stage so I will see what I can do.

Just to make sure I'm clear on your vision, we simply export all the functions from the SDK, people can then use them as they need? 

Or are you thinking about a chaining mechanism similar to esc-pos-encoder? 

I imagine if we expose them initially, a second step could be some sort of chaining mechanism...

**Comment by tr3v3r** [comment]
@zchryst Yeap, I thought about the chaining mechanism. I thought to make something like:
1)
```
printing
.feed()
.printText(''text")
.printImage(require('./....')) // returns something like [['feed'], ['printText', 'text'], ['printImage', number]]

```
then pass the returned array into the native side and process received data by invoking corresponding methods of the SDK.

Looks a bit complex but it will allow us not to make a lot of calls through the Bridge
 
2) Another way is just to invoke the desired method in sequence
```
await feed(); // invokes corresponding method of the SDK
await printText(''text");  // invokes corresponding method of the SDK
await printImage(require('./....'));  // invokes corresponding method of the SDK
```
PROS: Easy to implement
CONS: Every method will make a call through the bridge and should have its own error handling. 
Also, we need to think about how to mark this sequence as a single task on the native side ( to prevent conflicts between printer operations )

**Comment by tr3v3r** [comment]
Version 0.15.0 now supports image printing! 🎉 🎉🎉🎉
Sanks to @zchryst  and @echoneet
