### ISSUE TITLE
Emulator Support

### ISSUE THREAD

**Issue by vrdevrocket** [tr3v3r/react-native-esc-pos-printer#83]
Hi, First of all, I want to thank you for keeping the library updated and adding new features.
Do you have any plan to add Emulator support for it?

I saw we are using React-native-esc-pos as the main library behind it and I tried that on an emulator and it worked well.

**Comment by tr3v3r** [comment]
@vrdevrocket hi!
This limitation goes from Epson Android SDK itself. You can build your app on Android Emulator, but discover method will not find any printers (at least with the LAN connection ). That because your device and printer **must be in the same network**, but if you take a look at Emulator IP you will see that it uses it's own default one. This missmatch is  actually the reason of this issue. 

To be honest I didn't try any other types of connections ( WiFI or BLE ). Probably they work

**Comment by vrdevrocket** [comment]
Thank you for your answer.
Oh, I see.
What about adding printer IP manually to print instead of selecting from the discover function?
What do you think?

**Comment by tr3v3r** [comment]
@vrdevrocket  I've made quick tests about a year or two ago but didn't manage to do that 
I'd really appreciate if someone could make one more investigation on it !

**Comment by vrdevrocket** [comment]
@tr3v3r It'll be great if you give me something so I be in touch with you because I've already manually added IP with the base library or "React-native-esc-pos".

Maybe we can handle it and add it to your project?

**Comment by tr3v3r** [comment]
@tr3v3r  you can write me directly on email.
It should be vidilbe in my account  details

**Comment by tr3v3r** [comment]
Closed since this is a limitation from Android SDK highlighted in docs (https://github.com/tr3v3r/react-native-esc-pos-printer/issues/83#issuecomment-1367757086)
