### ISSUE TITLE
Monitoring Multiple Printers and reach stability

### ISSUE THREAD

**Issue by jevonch** [tr3v3r/react-native-esc-pos-printer#96]
Hello @tr3v3r , thank you for creating this library. I have some questions after doing some trial in production. 
1. Is it true that we need to InitPrinter when the device is going offline ( status.online ) OR disconnected ( status.connection )? 

2. how do i manage multiple printers? in this case, I used 5 printers. Is it a best practice to init printer everytime I need to print? 

Thank for

**Comment by Rehankhalil462** [comment]
@jevonch  2- It is best practice to test your connection before printing. Otherwise , what you can do is , if you are going to print from 1 printer , then you just have to init that for one time , and then you can use that to print your further things. 
But when you would like to print from another printer , as you told that you have 5 printers, then you have to init that another printer first, and then you can follow the same steps to print .

**Comment by jevonch** [comment]
when I init another print, before moving to second printer. do I need to disconnect the first one?
 
you’ve said best practive to test the conection. it means, I need to startmonitoring and then stop monitoring after printing. is it true?

**Comment by Rehankhalil462** [comment]
@jevonch when you would connect with the printer using `init` method , then to connect with 2nd one you don't need to disconnect. You can connect right after using init method. 

And you don't need to start  and stop monitoring  while connecting and disconnecting.  

Just test the connection by printing a simple text , if it would not be successful, I mean device  would not be connected, then you will get an error of `ERR_CONNECT` and then you can handle this error and do whatever you want ( connect with another available one etc).

**Comment by tr3v3r** [comment]
Check version 4.0.0.
